language: rust

rust:
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc

after_success:
  test $TRAVIS_PULL_REQUEST == "false" &&
  test $TRAVIS_BRANCH == "master" &&
  ./etc/deploy-docs.sh
