[package]
name = "rustty"
version = "0.1.0"
authors = ["Cole Reynolds <cpjreynolds@gmail.com>"]

[dependencies]
libc = "0.1.6"

[dependencies.rust-bindgen]
git = "https://github.com/crabtw/rust-bindgen.git"
