[package]
name = "rustty"
version = "0.1.0"
authors = ["Cole Reynolds <cpjreynolds@gmail.com>"]
description = "Pure Rust termbox implementation."
documentation = "https://cpjreynolds.github.com/rustty"
repository = "https://github.com/cpjreynolds/rustty"
readme = "README.md"
license = "MIT"

[dependencies]
libc = "0.1.6"
nix = "0.3.5"

