[package]
name = "rustty"
version = "0.0.1"
authors = ["Cole Reynolds <cpjreynolds@gmail.com>"]
description = "Library for creating textual user interfaces."
documentation = "https://cpjreynolds.github.com/rustty"
repository = "https://github.com/cpjreynolds/rustty"
readme = "README.md"
license = "MIT"

[lib]
name = "rustty"
path = "src/lib.rs"

[dependencies]
time = "*"
nix = "*"

