[package]
name = "rustty"
version = "0.0.1"
authors = ["Cole Reynolds <cpjreynolds@gmail.com>"]
description = "Pure Rust termbox implementation."
documentation = "https://cpjreynolds.github.com/rustty"
repository = "https://github.com/cpjreynolds/rustty"
readme = "README.md"
license = "MIT"

[dependencies]
libc = "*"
nix = "*"
bitflags = "*"
time = "*"
